"""add task execution history

Revision ID: 552021575263
Revises: 4af5e7bece46
Create Date: 2026-08-20 12:19:13.468121
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '552021575263'
down_revision: Union[str, Sequence[str], None] = '4af5e7bece46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###