"""add message created at index

Revision ID: ed50dd3a9a9c
Revises: 9cc0ba43bceb
Create Date: 2026-08-18 21:07:53.848066
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed50dd3a9a9c'
down_revision: Union[str, Sequence[str], None] = '9cc0ba43bceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    # ### end Alembic commands ###